### ISSUE TITLE
Providing an ?w=100 parameter results in an 500 error

### ISSUE THREAD

**Issue by lucacastelnuovo** [hauxir/imgpush#20]
My `docker-compose.yml` looks like this:
```yaml
version: "3.5"
services:
  imgpush:
    build: .
    ports:
      - 82:5000
    environment:
      #- OUTPUT_TYPE="jpg"
      - MAX_SIZE_MB=16
      - MAX_UPLOADS_PER_DAY="1000"
      - MAX_UPLOADS_PER_HOUR="100"
      - MAX_UPLOADS_PER_MINUTE="20"
      #- ALLOWED_ORIGINS=['https://assets.castelnuovo.nl', 'https://admin.sluijterkappers.nl']
      - VALID_SIZES=[100,200,300]
      - NAME_STRATEGY="uuidv4"
    volumes:
      - ./app:/app
      - ./images:/images
      - ./cache:/cache
```

If I open an normal link it just works, but if I add an `?w=100` I get an 500 code.

I have also tried setting it like `- VALID_SIZES="[100,200,300]"` but also doesn't work.
