### ISSUE TITLE
fix docker-compose

### ISSUE THREAD

**Issue by onvrb** [hauxir/imgpush#22]
exposing `/app` folder makes the container not find the entrypoint.sh

**Comment by onvrb** [comment]
also, when starting the container, it errors the parameter "start_period" in healthcheck. (I don't know why, I don't know how to use healthcheck).

**Comment by SmartPhoneLover** [comment]
It stills not fixed. Any progress?

**Comment by onvrb** [comment]
> It stills not fixed. Any progress?

Check PR #29 . Just expose the volume /images to your host. You can also delete lines start_period, test and interval if you're not using a cluster.

**Comment by SmartPhoneLover** [comment]
> > It stills not fixed. Any progress?
> 
> Check PR #29 . Just expose the volume /images to your host. You can also delete lines start_period, test and interval if you're not using a cluster.

Yeah, I already mapped the '/images' internal directory, also de '/cache'. Thank you ;)

**Comment by averatec1337** [comment]
In case you don't want to clone this repo just use this service in docker-compose:
```
    imgpush:
        image: hauxir/imgpush:latest
        container_name: imgpush
        volumes:
            - data-images:/images
        ports:
            - "5000:5000"
        environment:
            - MAX_UPLOADS_PER_MINUTE=100
            - MAX_UPLOADS_PER_HOUR=5000
            - MAX_UPLOADS_PER_DAY=100000
            - VALID_SIZES=[150,300,600,900,1200]
            - NAME_STRATEGY=uuidv4
```

Don't forget to change environment variables and add data-images volume or change it to the bind
